.docker-config:
  script: |
    DOCKER_BUILD_ARGS="--build-arg BASE_IMAGE=${BASE_IMAGE} --build-arg PYTHON_VERSION=3.9"

    DOCKER_CFG="{\"auths\":{"

    DOCKER_CFG="${DOCKER_CFG}\"${DOCKERHUB_REGISTRY}\":{\"auth\":\"$(echo -n "${DOCKERHUB_USERNAME}:${DOCKERHUB_PASSWORD}" | base64)\"},"
    DOCKER_CFG="${DOCKER_CFG}\"${GHCR_REGISTRY}\":{\"auth\":\"$(echo -n "${GHCR_USERNAME}:${GHCR_PASSWORD}" | base64)\"}"

    DOCKER_CFG="${DOCKER_CFG}}"

    DOCKER_TAG=dev
    if [ "x${CI_COMMIT_TAG}" != "x" ]; then
      DOCKER_TAG=${CI_COMMIT_TAG}
    elif [ "${CI_COMMIT_BRANCH}" == "${CI_DEFAULT_BRANCH}" ]; then
      DOCKER_TAG=latest
    fi
    DOCKER_CFG="${DOCKER_CFG} }"

    KANIKO_BUILD_ARGS="--reproducible --snapshot-mode time --use-new-run --cache --cache-repo ${GHCR_REPO}/cache"

    KANIKO_PUSH_ARGS="\
      --destination ${DOCKERHUB_REPO}:${DOCKER_TAG}${TAG_POSTFIX}\
      --destination ${GHCR_REPO}:${DOCKER_TAG}${TAG_POSTFIX}\
    "

    REGISTRIES="DOCKERHUB GHCR"