# Ensures that we do an out of source build

MACRO(MACRO_ENSURE_OUT_OF_SOURCE_BUILD MSG)
    STRING(COMPARE EQUAL "${PROJECT_SOURCE_DIR}"
"${PROJECT_BINARY_DIR}" insource)
    GET_FILENAME_COMPONENT(PARENTDIR ${PROJECT_SOURCE_DIR} PATH)
    STRING(COMPARE EQUAL "${PROJECT_SOURCE_DIR}"
"${PARENTDIR}" insourcesubdir)
    IF(insource OR insourcesubdir)
        MESSAGE(FATAL_ERROR "${MSG}")
    ENDIF(insource OR insourcesubdir)
ENDMACRO(MACRO_ENSURE_OUT_OF_SOURCE_BUILD)
