name: clang-format-lint

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: '.'
        extensions: 'h,hpp,cpp'
        exclude: './third-party ./cmake ./docker ./snap ./modules/tools/contrib ./modules/camera/include/ifm3d/contrib'
        clangFormatVersion: 10

